version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123qwe!@#
      POSTGRES_DB: dragonbox_db
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres_compose_network

  pdadmin_compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: careycoder@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123qwe!@#
    depends_on:
      - db
    ports:
      - 5050:80
    networks:
      - postgres_compose_network

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

networks:
  postgres_compose_network:
    driver: bridge
